const GET_SPECIFIC_ADS = 'GET_SPECIFIC_ADS'
const GET_SPECIFIC_ADS_SUCCESS = 'GET_SPECIFIC_ADS_SUCCESS'
const GET_SPECIFIC_ADS_FAILURE = 'GET_SPECIFIC_ADS_FAILURE'

export { GET_SPECIFIC_ADS, GET_SPECIFIC_ADS_SUCCESS, GET_SPECIFIC_ADS_FAILURE }
