const GET_USER_ADS = 'GET_USER_ADS'
const GET_USER_ADS_SUCCESS = 'GET_USER_ADS_SUCCESS'
const GET_USER_ADS_FAILURE = 'GET_USER_ADS_FAILURE'

export { GET_USER_ADS, GET_USER_ADS_SUCCESS, GET_USER_ADS_FAILURE }
