const GET_LOGIN_DATA = 'GET_LOGIN_DATA'
const GET_LOGIN_DATA_SUCCESS = 'GET_LOGIN_DATA_SUCCESS'
const GET_LOGIN_DATA_FAILURE = 'GET_LOGIN_DATA_FAILURE'

export {
  GET_LOGIN_DATA,
  GET_LOGIN_DATA_SUCCESS,
  GET_LOGIN_DATA_FAILURE,
}