const LOGIN_USER = 'LOGIN_USER'
const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
const CREATE_USER = 'CREATE_USER'
const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'
const LOGOUT_USER = 'LOGOUT_USER'
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export {
  LOGIN_USER,
  LOGIN_USER_SUCCESS,
  LOGIN_USER_FAILURE,
  CREATE_USER,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILURE,
  LOGOUT_USER,
  LOGOUT_USER_SUCCESS,
  LOGOUT_USER_FAILURE,
}
