const GET_LOGIN_DATA = 'GET_LOGIN_DATA'
const GET_LOGIN_DATA_SUCCESS = 'GET_LOGIN_DATA_SUCCESS'
const GET_LOGIN_DATA_FAILURE = 'GET_LOGIN_DATA_FAILURE'
const CREATE_USER = 'CREATE_USER'
const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS'
const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE'

export {
  GET_LOGIN_DATA,
  GET_LOGIN_DATA_SUCCESS,
  GET_LOGIN_DATA_FAILURE,
  CREATE_USER,
  CREATE_USER_SUCCESS,
  CREATE_USER_FAILURE,
}
