const CREATE_USER_IN_DB = 'CREATE_USER_IN_DB'
const CREATE_USER_IN_DB_SUCCESS = 'CREATE_USER_IN_DB_SUCCESS'
const CREATE_USER_IN_DB_FAILURE = 'CREATE_USER_IN_DB_FAILURE'

export {
  CREATE_USER_IN_DB,
  CREATE_USER_IN_DB_SUCCESS,
  CREATE_USER_IN_DB_FAILURE,
}
