const LOGOUT_USER = 'LOGOUT_USER'
const LOGOUT_USER_SUCCESS = 'LOGOUT_USER_SUCCESS'
const LOGOUT_USER_FAILURE = 'LOGOUT_USER_FAILURE'

export { LOGOUT_USER, LOGOUT_USER_SUCCESS, LOGOUT_USER_FAILURE }
