const UPDATES_AD_EMPLOYEES = 'UPDATES_AD_EMPLOYEES'
const UPDATES_AD_EMPLOYEES_SUCCESS = 'UPDATES_AD_EMPLOYEES_SUCCESS'
const UPDATES_AD_EMPLOYEES_FAILURE = 'UPDATES_AD_EMPLOYEES_FAILURE'

export {
  UPDATES_AD_EMPLOYEES,
  UPDATES_AD_EMPLOYEES_SUCCESS,
  UPDATES_AD_EMPLOYEES_FAILURE,
}
